version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/New_York
  open-pull-requests-limit: 30
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/New_York
  open-pull-requests-limit: 30
  ignore:
  - dependency-name: github.com/open-policy-agent/opa
    versions:
    - 0.27.1
