steps:
      - name: Accurics
        uses: accurics/accurics-action@v1.0
        id: accurics
        with:
          app-id: ${{ secrets.ACCURICS_APP_ID }}
          env-id: ${{ secrets.ACCURICS_ENV_ID }}
